# Generated by Django 3.0.3 on 2020-06-04 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_name', models.CharField(max_length=128)),
                ('Tablet_or_Syrup', models.CharField(choices=[('Cap', 'Capsule'), ('Syr', 'Syrup'), ('Tab', 'Tablet'), ('Susp', 'Susp'), ('Oint', 'Ointment'), ('Drop', 'Drop'), ('O', 'Other')], max_length=5)),
                ('Ingredient_Drugs', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=128)),
                ('patient_age', models.IntegerField()),
                ('first_visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_address', models.CharField(max_length=256)),
                ('patient_weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other_comments', models.CharField(blank=True, default='None', max_length=256)),
                ('blood_pressure', models.CharField(blank=True, max_length=64)),
                ('RS', models.CharField(blank=True, default='NAD', max_length=128)),
                ('CVS', models.CharField(blank=True, default='NAD', max_length=128)),
                ('ut', models.CharField(blank=True, max_length=64)),
                ('vx', models.CharField(blank=True, max_length=64)),
                ('FHS', models.CharField(blank=True, max_length=64)),
                ('PIV', models.CharField(blank=True, max_length=64)),
                ('H_O', models.TextField(blank=True, max_length=256)),
                ('C_O', models.TextField(blank=True, max_length=256)),
                ('gravida', models.CharField(blank=True, max_length=2)),
                ('para', models.CharField(blank=True, max_length=2)),
                ('abortions', models.CharField(blank=True, max_length=2)),
                ('fees', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient_entry.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('dose', models.CharField(blank=True, choices=[('1', 'Once a day'), ('2', '2 times/day'), ('3', '3 times/day'), ('0', 'Other')], max_length=1)),
                ('medicine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines_prescription_record', to='patient_entry.Medicines')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_prescription_record', to='patient_entry.Prescription')),
            ],
        ),
    ]
