# Generated by Django 3.0.3 on 2020-06-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_entry', '0002_auto_20200604_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='Tablet_or_Syrup',
            field=models.CharField(choices=[('Cap', 'Capsule'), ('Syr', 'Syrup'), ('Tab', 'Tablet'), ('Susp', 'Susp'), ('Oint', 'Ointment'), ('Drop', 'Drop'), ('Pow', 'Powder'), ('Inj', 'Injection'), ('O', 'Other')], max_length=5),
        ),
    ]
